<?php

namespace WebsiteBundle\Repository;

/**
 * AmbasadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmbasadorRepository extends \Doctrine\ORM\EntityRepository
{
}
