<?php

namespace WebsiteBundle\Repository;

/**
 * CenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenterRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        $qb = $this->_em->createQueryBuilder('c');
        $qb->select($qb->expr()->count('c.id'));
        $qb->from('WebsiteBundle:Center','c');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
