<?php

namespace WebsiteBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        $qb = $this->_em->createQueryBuilder('e');
        $qb->select($qb->expr()->count('e.id'));
        $qb->from('WebsiteBundle:Event','e');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
