<?php

namespace WebsiteBundle\Repository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        $qb = $this->_em->createQueryBuilder('m');
        $qb->select($qb->expr()->count('m.id'));
        $qb->from('WebsiteBundle:Member','m');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
