<?php

namespace WebsiteBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        $qb = $this->_em->createQueryBuilder('p');
        $qb->select($qb->expr()->count('p.id'));
        $qb->from('WebsiteBundle:Project','p');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
